language: java

jdk:
  - oraclejdk8
  - openjdk8
  
git:
  depth: false

addons:
  sonarcloud:
    organization: "svendiedrichsen-github"

script:
   - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package cobertura:cobertura coveralls:report; fi'
   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package cobertura:cobertura coveralls:report sonar:sonar; fi'
